### ISSUE TITLE
YAML Configurator not for A1 mini

### ISSUE THREAD

**Issue by JoveCat** [WolfwithSword/Bambu-HomeAssistant-Flows#1]
Your dashboards plug-in is great, but there is a problem. My printer is A1 mini. In the YAML Configurator, I selected A1 mini and AMS Lite, but in the generated yaml file, the image is always for X1. Is it because I didn’t select the right one? ?

**Comment by WolfwithSword** [comment]
> Your dashboards plug-in is great, but there is a problem. My printer is A1 mini. In the YAML Configurator, I selected A1 mini and AMS Lite, but in the generated yaml file, the image is always for X1. Is it because I didn’t select the right one? ?

Just checked and looks like I had a typo in the generative code.

Fix is live now, could you give it another try?
