### ISSUE TITLE
BambuLab Cloud MQTT Restrictions

### ISSUE THREAD

**Issue by mkosmo** [WolfwithSword/Bambu-HomeAssistant-Flows#10]
Filing an issue for awareness:  Not sure if you saw this [forum post](https://forum.bambulab.com/t/bambu-lab-mqtt-limitations/83440), but I reckon the cloud MQTT connectivity may have had something to do with it.

Use of NodeRed/HA for Bambu cloud MQTT integration may result in service outages for users until they roll out their changes.

**Comment by WolfwithSword** [comment]
Although I'm still suspect of it happening with my flow, I did identify a specific condition with the cloud flow that could, if the cloud was unstable *during* a reconnect attempt, it could accumulate reconnect loops in parallel, and this may grow over time.

This explains the reconnect and new client Id's they mentioned, but does not explain how the clients stayed connected, as they would have been disconnected by NodeRed.

Either way, I am pushing a 2.1.6 emergency update for the basic flow for this. It also includes hard-setting a client ID to make future stuff easier to identify.
