### ISSUE TITLE
Link down?

### ISSUE THREAD

**Issue by andybali** [WolfwithSword/Bambu-HomeAssistant-Flows#17]
Link to Media files down?
https://nightly.link/WolfwithSword/Bambu-HomeAssistant-Flows/workflows/media_archive/main/bambu-ha-media-files.zip

**Comment by WolfwithSword** [comment]
Yeah nightly.link is currently down - not sure how long it will be down for. In the meantime while I am looking at backups/alternatives (that don't trigger random malicious scans as half of the options do), you can download the latest from here:

[bambu-ha-media-files.zip](https://github.com/user-attachments/files/17870144/bambu-ha-media-files.zip)

**Comment by WolfwithSword** [comment]
Update: Made a workflow to build a nightly release on any change to media folder contents, and this link should now work.

Will update it on the site to verify and close issue if it works 

https://github.com/WolfwithSword/Bambu-HomeAssistant-Flows/releases/download/nightly/bambu-ha-media-files.zip

**Comment by andybali** [comment]
thx... for update and fast response
