### ISSUE TITLE
Images not shown

### ISSUE THREAD

**Issue by amdjml** [WolfwithSword/Bambu-HomeAssistant-Flows#18]
Hi,

I have followed the guide on your site and downloaded the images and placed them in appropriate folders and I am still unable to see them when I go to my dashboard.

![Screenshot 2024-11-22 at 12 23 27 PM](https://github.com/user-attachments/assets/af85cd36-421e-447c-9836-96262116e931)
![Screenshot 2024-11-22 at 12 23 44 PM](https://github.com/user-attachments/assets/a1497cd5-a8b3-4a30-827e-70350ec4e53e)
![Screenshot 2024-11-22 at 12 22 57 PM](https://github.com/user-attachments/assets/03431587-c8da-4b64-8685-8d04ec6cdf01)

**Comment by WolfwithSword** [comment]
Refresh your browser cache or try another browser, and maybe restart home assistant once as well. It might just be a loading issue as that directory looks correct

**Comment by WolfwithSword** [comment]
Closing as no response - please reopen if this is still an issue after refreshing cache / reconfirming directory / reading the Common Problems section in the configuration page.
