### ISSUE TITLE
Advanced Flow

### ISSUE THREAD

**Issue by unixtall** [WolfwithSword/Bambu-HomeAssistant-Flows#2]
Hi, i'm trying to import the adavanced flow, but when i click to startup set, and error appears. I dont know if i have to connect something. Could you help me?

_**"Advanced Flow cannot be used without the Basic Flow group in the same flow."**_

**Comment by WolfwithSword** [comment]
Yes, you're supposed to have these groups within the same flow/tab in NodeRed, essentially one flow/tab per printer, and the advanced flow (or other misc flows) go in the same as each printer's basic flow.

The only exception is the optional bambu cloud login flow, you only need one of those and it's shared between all printers/flows.

After importing it into the same flow, all you need to do is deploy and it should work.
